names = [
    "5JYT",
    "7BNY"
]
tags = [
    [
        "5JYT"
    ],
    [
        "7BNY"
    ]

]
seqs = [
    [
        "MAPLRKTAVLKLYVAGNTPNSVRALKTLANILEKEFKGVYALKVIDVLKNPQLAEEDKILATPTLAKVLPPPVRRIIGDLSNREKVLIALRLLAEEIGDYKDDDDK"
    ],
    [
        "SPNPLDVSKTYPTLHILLQFNHRGLEARIFRHGQLWAETHAEVVLRSKTKQISFLSNGSYPSMDATTPLNPWKSTYQAVLRAEPHRVTMDVYHKRIRPFRLPLVQKEWRTCEENVFGLYHVFETHYAGYFSDLLIHDVETNPGGSKHHHHHH"
    ]
]